api_platform:
    title: 'Symfony REST API'
    description: 'A Symfony API to manage a website Pharmacy'
    version: '2.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]